### ISSUE TITLE
Payment via api for custom module

### ISSUE THREAD

**Issue by A-linea** [remp2020/crm-payments-module#19]
Hello Peter! 
I didn't know where to write my question, so I'm asking here. We have the following situation, we have a payment system similar to stripe. I am currently writing a custom module for it called myCustomPaymentModule. 

We are doing the following implementation: our website displays payment options, there are many of them, but I want to analyze at least one, the user clicks on the payment, and through the api I want to pass all the data for the crm-skeleton to my MyCustomPaymentModue. 

In this module, I open the api endpoint, and there is some kind of handler that should return the checkoutPage from the payment system to our site. Initially, I had an idea to call an intermediate request from the CRM itself after the necessary data comes through the api, something like `httpClient->post('/sales-funnel/sales-funnel-frontend/submit', $data) `so that all customer data is stored in the CRM and analytics works, but I faced the problem that if I return checkouturl, then all the logic in the CRM breaks down.

 If I have clearly described the problem, please tell me in which direction and where to look so that crm acts only as a mediator and stores all intermediate results eg falied, paid, proceeded, etc. and the payment buttons themselves are on our site, and all responses from the payment system are also received by our site, but also through crm to record everything in the database? Do we need to write a new sales-funnel implementation or is there an even better way to implement it through the api?

Thank you!

UPD
ATM I reilized custom $gateway->process(), $gateway->getResponseData(), $gateway->isSuccessful methods in my GenericGateway, and now i can return url in $gateway->process method looks like everething works

Maybe we have better way.

**Comment by rootpd** [comment]
Hi, the comment you updated in UPD is basically right.

The idea is:

- You submit the sales funnel with selected gateway, subscription type, user info, ...
- CRM stores everything and creates payment in the "form" (unpaid) state.
- Then the payment processing starts. Sales funnel module calls this:
  ```php
  $result = $this->paymentProcessor->begin($payment, $this->isAllowedRedirect());
  ```
  Which internally calls this:
  ```php
  $gateway->begin($payment);
  // ...
  $gateway->process($payment);
  ```

At this moment, two things can happen, depending on whether your sales funnel indicated it's capable of processing the response from the server itself through the `allow_redirect` POST parameter (see [README](https://github.com/remp2020/crm-salesfunnel-module)).

_Important note: If you use `allow_redirect` POST parameter, submit the funnel via AJAX, so you can process the response._

- The gateway can return `redirectResponse` and the user will be automatically redirected away to process the payment.
- Or the sales funnel indicated that it's capable of handling non-redirect scenario and the gateway only returns processed data. The default is this:
  ```php
  return new ProcessResponse('url', $this->response->getRedirectUrl());
  ```
  This gets JSON-encoded and returned back to the JS client for further processing.

You can see both scenarios live:

- The redirect handler can be seen at https://predplatne.dennikn.sk (select the card payment).
- The AJAX + custom processing can be seen at https://predplatne.denikn.cz (select the card payment). CRM returns URL of the checkout page and sales funnel displays it in the modal iframe.

If your gateway returns something else than URL (for example full HTML), can create your own `ProcessResponse` within `process()` method of your gateway.

**Comment by A-linea** [comment]
Thanks for the answer, I will try different options. We will have multiple funnels, each with multiple payment methods and subscription types. I've almost got it figured out, now I just need to adapt everything to our needs.

**Comment by A-linea** [comment]
Hello, Peter!  
I need your help! When does the complete method trigger (for example, in BaseGoPay or crm-stripe-module/src/Gateways/AbstractStripe.php) and how to implement it better for the api. I did not find where it is called in these two modules, only implemented from Interface . Thanks!

**Comment by rootpd** [comment]
Hi,

the usual flow with `complete()` at the payment gateways is this:

- You initialize the payment at the level of CMS (`begin()`, `process()`). During this initialization, gateway usually asks for the URL where user is redirected if the payment is successful.
- Then the gateway returns you the URL of the page which processes the payment. CRM either redirects the user there or you display the contents to user yourself (we discussed this above).
- If everything is OK, gateway returns user to the URL provided in step one. By default, it's directed to `/payments/return/gateway/%GATEWAY_CODE%`. There the `Gateway::complete()` is called and payment is finally confirmed on CRM's side.

GoPay has another level of confirmation which requires API webhook to be called by Gopay. The process continues:

- In the `Gateway::complete()`, you read the query params and confirm with the gateway that the payment went though. Some gateways provide you with hash you verify locally, some gateways let you check the payment status via API. It differs.
- With Gopay, we call Status API and it usually ends with `PENDING_PAYMENT_SUB_STATE` (payment is still pending). That means that everything was OK so far, but the payment wasn't settled yet and we have to wait.
- Then Gopay hits the API (`GoPayNotificationHandler`). From there, the handler calls `BaseGoPay::notification()` which contains processing of notification params . Only here the payment usually gets actually confirmed.

Stripe is completely different :). With Stripe, a lot of can happen directly on frontend in JS library. 

- In sales funnel's frontend, you can enter your card data and let Stripe to generate you "payment method". This is stored to `payment_meta` when funnel is submitted.
- `Stripe::begin()` reads this and if it finds that the data was collected, calls `AbstractStripe::processSetupIntent()`.
- There (still within `begin()`) happens basically all payment processing. If Stripe requires redirect, we redirect user away just as with any other `begin()` call. But at this point, Stripe can also say that the [payment was already successful](https://github.com/remp2020/crm-stripe-module/blob/master/src/Gateways/AbstractStripe.php#L182). In that case, we redirect user to the "return URL" that I mentioned at the beginning of comment.
- After redirect, standard `complete()` flow is executed with payment verification against Stripe API and payment confirmation on the side of CRM.

If you have some other flow in mind / under your hands, let me know :slightly_smiling_face: .

**Comment by A-linea** [comment]
Thank you! Our flow after checkout is more like Gopay, I'm opening an endpoint callback API where hooks from the payment system will come. If I understood correctly, the "complete" method in Gopay is located in Omnipay\GoPay\Gateway::complete(). Therefore, in our case, after processing the POST request in my CallbackApiHandler, I simply call the method in myGenericGateway handleCallback() as an example, which processes the callback itself and, accordingly, depending on the statuses, changes them for the current payment.


And another question, please, through the callback we can get about 114 types of payment errors, so as not to get into the code core and, I thought about storing them in the "payments" table in "error_message" field when I change the payment status, but unfortunately I did not see this field displayed in the admin CRM, maybe I missed something. Thank you very much, you helped me a lot.

**Comment by rootpd** [comment]
**Flow:** Yes, that's correct.

**Error codes:** Wow, the `error_message` fields is something historical. Let's ignore that for now. I don't see single payment or part of code actually using this field :). 

For this scenario there's table called `payment_logs` which links to the payment and is precisely dedicated for storing responses from the payment gateways. You can see that also Gopay's notification handler is calling that and storing the data in there:

https://github.com/remp2020/crm-gopay-module/blob/master/src/Gateways/BaseGoPay.php#L155

But even data from this table aren't display in CRM admin anywhere, mainly because there's no standard on what kind of data/errors gateways can return.

The best for you would be create a very simple widget (https://github.com/remp2020/crm-skeleton/#registerwidgets), which would be attached to the payment listing in CRM admin. If the payment failed and used your gateway, you'd display extra information based on what you find in the `payment_logs` table. That would also give you an option not just to display error codes, but actually messages with some meaning so the CRM Admin user understands, what's happening.

Attaching the widget to `admin.payments.user_payments_listing.badge` position (right next to the note) seems like a good place to me.

**Comment by A-linea** [comment]
Yes, thanks, that's what I'm going to do, a custom widget where I will display several fields with error codes and descriptions of these errors!

**Comment by A-linea** [comment]
Hi Peter. I apologise for writing in this thread, I decided not to create new issues. At the moment, I am at the stage of setting up CRM-Skeleton for sending emails.


I will say right away that all this is local, without a docker, m2 macOS Ventura 13.4

1. The first point is that crm-skeleton/vendor/remp/crm-remp-mailer-module and https://github.com/remp2020/mailer-module are the same thing, am I right?
Then the question is why I need https://github.com/remp2020/mailer-skeleton because it seems uses the same dependency. I didn't fully understand this point.

Nevertheless, I installed https://github.com/remp2020/mailer-skeleton
and started all the workers, 
```
php bin/command.php scenarios:worker
php bin/command.php application:hermes_worker
bin/command.php mail:process-job
```
configured mailhog, redis,  made changes to nginx.config. And everything worked. I have not found anywhere how to link crm-skeleton and mailer-skeleton. What additional configuration steps do I need to take? 
They work through redis, but can they use the same one, for example, at` 127.0.0.1:6379` ? Thank you very much for your help! Have a nice evening!

**Comment by rootpd** [comment]
@A-linea I saw a message notification in email, but the message isn't here. I'm not sure whether you deleted it or it's some kind of Github bug. Nevertheless, I've enabled discussions on this repo (https://github.com/remp2020/crm-payments-module/discussions), we can continue there if necessary.

**Comment by A-linea** [comment]
Hi Peter. I apologise for writing in this thread, I decided to delete it, but ATM for not to create new issues reversed it. At the moment, I am at the stage of setting up CRM-Skeleton for sending emails.

I will say right away that all this is local, without a docker, m2 macOS Ventura 13.4

The first point is that crm-skeleton/vendor/remp/crm-remp-mailer-module and https://github.com/remp2020/mailer-module are the same thing, am I right?
Then the question is why I need https://github.com/remp2020/mailer-skeleton because it seems uses the same dependency. I didn't fully understand this point.
Nevertheless, I installed https://github.com/remp2020/mailer-skeleton
and started all the workers,

php bin/command.php scenarios:worker
php bin/command.php application:hermes_worker
bin/command.php mail:process-job
configured mailhog, redis, made changes to nginx.config. And everything worked. I have not found anywhere how to link crm-skeleton and mailer-skeleton. What additional configuration steps do I need to take?
They work through redis, but can they use the same one, for example, at 127.0.0.1:6379 ? Thank you very much for your help! Have a nice evening!

**Comment by rootpd** [comment]
Mailer - those two are different :slightly_smiling_face: . 

- Mailer Skeleton is a separate app for managing emails/templates and sending emails.
- CRM REMP Mailer module is a module to CRM, which integrates CRM with Mailer. When CRM wants to send an email, it calls Mailer's API to actually send it. Without it, CRM wouldn't be able to send emails and you'd have to create your own integration to the email provider of your choice.

**How to link:** If the module is used in CRM, it should be configured based on the README: https://github.com/remp2020/crm-remp-mailer-module#enabling-and-configuring-module. Enable the extension and put Mailer's URL and API token into `config.neon` file.

The way they communicate is through APIs, so Redis/Mysql/whatever else should **not** be shared. Otherwise they would try to execute each others' events and fail :slightly_smiling_face: .

**Comment by A-linea** [comment]
Omg, thank you my bad. I looked at the documentation for another module.
