### ISSUE TITLE
`postal_fee_id` column in table `payment_items` is missing

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-payments-module#6]
Bug is for example in `/payments/payments-admin/edit/`
```
Nette\MemberAccessException: Cannot read an undeclared column 'postal_fee_id'. in /data/www/wbn_remp/Crm/vendor/nette/database/src/Database/Table/ActiveRow.php:299  @  http://??????/payments/payments-admin/edit/9075?userId=6 
```
there is just needed to add that to the migrations file

**Comment by rootpd** [comment]
Already fixed in `0.11.0`, please update your CRM.

https://github.com/remp2020/crm-payments-module/commit/bb836827981a78b3f510dceb68989291c5732bb8
